name: Deploy Wello Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          script: |
            set -e

            echo "📂 Moving to project..."
            cd /var/www/Wello-Healthcare

            echo "⬇️ Pulling latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "📦 Installing dependencies..."
            npm install

            echo "🏗️ Building Next.js application..."
            npm run build

            echo "🚀 Restarting PM2..."
            pm2 restart wello-frontend

            echo "💾 Saving PM2..."
            pm2 save

            echo "✅ Wello Frontend deployed successfully."
